#elk:
#  image: qnib/elk
#  ports:
#   - "9200:9200"
#   - "5514:5514"
#   - "55514:55514/udp"
#   - "5601:5601"
#   - "8080:80"
#   - "8500:8500"
#  environment:
#  - DC_NAME=dc1
#  - RUN_SERVER=true
#  - BOOTSTRAP_CONSUL=true
#  - COLLECT_METRICS=false
#  - FORWARD_TO_LOGSTASH=false
#  dns: 127.0.0.1
#  hostname: elk
#  volumes: 
#   - /var/lib/elasticsearch
#  privileged: true

kibana:
  image: kibana
#  ports:
#    - "5601:5601"
  links:
    - elasticsearch

elasticsearch:
  image: elasticsearch
  volumes:
    - "$PWD/esdata:/usr/share/elasticsearch/data"
#  ports:
#    - "9200:9200"

nginx:
  image: nginx
  ports:
    - "5602:443"
  links:
    - kibana
  volumes:
    - "$PWD/certificate.crt:/etc/nginx/ssl/certificate.crt"
    - "$PWD/certificate.key:/etc/nginx/ssl/certificate.key"
    - "$PWD/kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd"
    - "$PWD/default.conf:/etc/nginx/conf.d/default.conf"